name: Meu primeiro CI


on:
  push:
    branches:
      - main

jobs:
  primeiro-job:
    runs-on: ubuntu-latest


    steps:
      - name: Mostrar sistema
        run: |
          echo "=== SISTEMA ==="
          uname -a
          echo ""
          echo "=== DIRETORIO ATUAL ==="
          pwd
          echo ""
          echo "=== ARQUIVOS ==="
          ls -la

      - name: Mostrar mensagem
        run: echo "Olá! Meu primeiro pipeline CI/CD está funcionando!"

      - name: Teste
        run: |
          echo "Executando teste..."
          test 1 -eq 1
          echo "Teste aprovado"
